name: Deploy to EoPages Web

on:
  #  push:
  #    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: dist
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.8.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy to EoPages
        run: pnpm run build-web
        env:
          EO_PAGES_TOKEN: ${{ secrets.EO_PAGES_TOKEN }}
